### PR TITLE
GPU tests

### PR DESCRIPTION
**Pull request by Randl**

### CODE REVIEW

**Comment by edgarriba** [comment]
@Randl that's cool. Just few comments:
1) You can directly PR to the project, not to my fork.
2) Not sure if having a try/catch is a good practice in a test.

For GPU tests I was thinking more in having a separate binary in order to trigger the tests by hand.
/cc @bhack @nyanp

**Comment by bhack** [comment]
Yes cause that cannot be executed in travis

**Comment by Randl** [comment]
@edgarriba 
1). I wasn't sure your fork is even with main repo
2). I haven't found better way to manage exceptions, else the test execution is interrupted. Am I missing something?

As for GPU tests, we may check if OpenCL is available before running them.

**Comment by edgarriba** [comment]
@Randl 
how did you do the rebase? your history is not lineal
http://stackoverflow.com/questions/7929369/how-to-rebase-local-branch-with-remote-master

**Comment by Randl** [comment]
@edgariba I'm doing it from IDE (CLion), but pretty sure that it does exactly this

**Comment by edgarriba** [comment]
Ok. But something is wrong with your git tree. Try to fix it. Besides that, also fix the travis issue on your PR

**Comment by Randl** [comment]
OK, I'll try to figure out what's the problem with the tree. And travis issue is fixed

**Pull request merged**
