### PR TITLE
Opencl ops patch

### PR DESCRIPTION
**Pull request by naibaf7**
LibDNN integration fix.

Note that dissecting the batch into multiple batches of size 1 is still a bad idea, performance wise.

The tuning probably won't help you much here, I left it out for initial testing. The kernels perform quite well in the default configuration for the following GPUs:
- nVidia: Kepler, Maxwell, Pascal (although there is a Pascal bug in CUDA 8.0 when padding is used)
- AMD: Tahiti, Hawaii, Tonga, Fiji, Polaris

For the second generation kernels that I am working on, tuning will be much more important, also to extend device support (Intel GPUs, mobile chips).

### CODE REVIEW

**Comment by edgarriba** [comment]
so, what makes the difference in setting `dev_ptr` as a class member?

**Comment by naibaf7** [comment]
@edgarriba 
Well... the object behind dev_ptr will be destroyed if you don't store the shared pointer in the class and keep it as a local function variable...
Getting the underlying pointer and putting it into the parameters for libDNN does not guarantee persistence of the object, the shared pointer also needs to stay within context.

I also added some access to the input device data after kernel execution, to make sure these don't get garbage collected before the kernel is done. Not sure if that is needed though, it's just for debugging. :)

**Comment by edgarriba** [comment]
@naibaf7 
right, I thought that device instance was only needed during kernel setup. But yes, now it seems to return back some values. I have to check now why are not the same as in the tests since for CPU device are that ones !

**Comment by naibaf7** [comment]
@edgarriba 
I see... no the device instance is also used during tuning and processing, to get details about the particular device.

As for the tuning, it seems the kernel finishes so fast, because it is so small, that the time division becomes NaN, and causes a division-by-zero exception at some point. I guess it would have to be tuned with a much larger batch size in order to get anything sensible out of it.

Hm, do you have a different convention for convolution output values? I don't get the numbers you did when computing the kernel by hand, interestingly. Could it be because the libDNN and cuDNN kernels (at least in Caffe) use the correlation instead of convolution (weights flipped)?
See: https://github.com/BVLC/caffe/issues/2513

But even if I compute convolution instead of correlation by hand, the values don't match.

**Comment by edgarriba** [comment]
alright, fixed !

The thing is that inside Conv2dLibDNNForwardOp we compute pure convolution. However, the test values are over convolutional layer which have an activation function. This is for historical reason and the motivation behind this OP style is to decouple layer types and activations.

BTW, what do you propose to benchmark tests using specific device? I mean as you had to change `platform_id` and `device_id`, other users will need to do the same.

/cc @bhack

**Comment by naibaf7** [comment]
@edgarriba 
I would create a script system to run benchmarks if I were you, and if the test API allows this.
The plattform-ID and device-ID should be command line parameters, or options that can be changed in the benchmark script (which could be in bash, python, or similar).

**Pull request merged**
