### PR TITLE
Serial type fix

### PR DESCRIPTION
**Pull request by beru**
Hi, this PR fixes tests with serialization.
@prlz77 should learn from this.

### CODE REVIEW

**Comment by beru** [comment]
This PR is for https://github.com/tiny-dnn/tiny-dnn/pull/747

**Comment by prlz77** [comment]
```
template <>
struct LoadAndConstruct<tiny_dnn::recurrent_cell_layer> {
  template <class Archive>
  static void load_and_construct(
    Archive &ar, cereal::construct<tiny_dnn::recurrent_cell_layer> &construct) {
    size_t in_dim, out_dim;
    bool has_bias;
    std::shared_ptr<tiny_dnn::activation_layer> activation{};
    arc(ar, make_nvp("in_size", in_dim), make_nvp("out_size", out_dim),
        make_nvp("has_bias", has_bias));
    auto al = tiny_dnn::layer::load_layer(ar);
    // a nullptr is passed to avoid creating unused activation layer.
    construct(in_dim, out_dim, has_bias, nullptr);
    // set the activation to the loaded value
    construct->set_activation(
      std::static_pointer_cast<tiny_dnn::activation_layer>(al));
  }
};
```
Could you please explain me in detail ``auto al = tiny_dnn::layer::load_layer(ar);``?

I don't see where ``std::shared_ptr<tiny_dnn::activation_layer> activation{};`` is used.

**Comment by beru** [comment]
> Could you please explain me in detail auto al = tiny_dnn::layer::load_layer(ar);?

Let me briefly explain `how serialization/deserialization code runs` to you.

# Serialization
- `network::save`

  It all stars from here. This is the beginning of serialization.

- `network::to_archive`
- `nodes::save_model`

  In here,  `oa(cereal::make_nvp("nodes", nodes_));` is used and the type of `nodes::nodes_` is `std::vector<layer *>` so, below function in `nodes.h` will be called by cereal.

```cpp
template <typename Archive>
void save(Archive &ar, const std::vector<tiny_dnn::layer *> &v) {
#ifndef CNN_NO_SERIALIZATION
  ar(cereal::make_size_tag(static_cast<cereal::size_type>(v.size())));
  for (auto n : v) {
    tiny_dnn::layer::save_layer(ar, *n);
  }
#else
  throw tiny_dnn::nn_error("tiny-dnn was not built with Serialization support");
#endif  // CNN_NO_SERIALIZATION
}
```

- layer::save_layer
- serialization_helper::save
- serialization_helper::save_layer_impl

```cpp
template <typename OutputArchive>
template <typename T>
void serialization_helper<OutputArchive>::save_layer_impl(OutputArchive &oa,
                                                          const layer *layer) {
  oa(cereal::make_nvp(
    serialization_helper<OutputArchive>::get_instance().type_name(typeid(T)),
    *dynamic_cast<const T *>(layer)));
}
```

`serialize` overloaded functions in `serialization_functions.h` file will be called by cereal.
Let's check the serialize function for `recurrent_cell_layer` class.

```cpp
  template <class Archive>
  static inline void serialize(Archive &ar,
                               tiny_dnn::recurrent_cell_layer &layer) {
    layer.serialize_prolog(ar);
    auto &params_ = layer.params_;
    arc(ar, make_nvp("in_size", params_.in_size_),
        make_nvp("out_size", params_.out_size_),
        make_nvp("has_bias", params_.has_bias_));
    tiny_dnn::layer::save_layer(ar, *params_.activation_);
  }
```

`layer::serialize_prolog` method.
```cpp
template <class Archive>
void layer::serialize_prolog(Archive &ar) {
  ar(cereal::make_nvp(
    "type",
    serialization_helper<Archive>::get_instance().type_name(typeid(*this))));
}
```
This method stores/loads its type_name. You can see type_names in `serialization_layer_list.h` file. It's pretty much meh that we can't use `layer::layer_type` method since it's virtual. 

All the layer serialize functions call `serialize_prolog` so I think we should move the call inside this function
```cpp
template <class Archive, typename T>
typename std::enable_if<std::is_base_of<tiny_dnn::layer, T>::value>::type
serialize(Archive &ar, T &layer) {
  serialization_buddy::serialize(ar, layer);
}
```
But that's a side story.

And I changed the code to use `layer::save_layer` static method to save an activation function member of the recurrent_cell_layer class. There are several reasons for the change such as reusing code, solving some problems with binary_archive (had to adjust things to save/load). I guess this is the most important part that should be explained in detail but I don't get any cash for this so you may explore the maze of the library with the help from your favourite text editor and debugger.

# Deserialization

This section is left empty to guide the reader's brain to burn calories.

------

> I don't see where std::shared_ptr<tiny_dnn::activation_layer> activation{}; is used.

Thank you for the notification. The local variable isn't used anymore. So I will remove it.

Your implementation had problems with existing mechanism of tiny-dnn library's serialize/deserialize code. The problem surfaced with test code that uses  binary_archive. So I took a different approach.

**Comment by prlz77** [comment]
Thank you! More or less I already understood the serialization procedure (prolog, archives, etc) but, as you have already noticed, I did not understand how you handled polymorphism. Anyway the explanation has been really helpful and ``tiny_dnn::layer::save_layer(ar, *params_.activation_);`` made me understand it all :smile: 

> This section is left empty to guide the reader's brain to burn calories.

I will try but unfortunately the PhD is already consuming a lot of them :wink:

**Pull request merged**
